# Generated by Django 3.1.6 on 2021-02-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='category',
            new_name='topic',
        ),
    ]
